[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my-app"
version = "0.1.0"
dependencies = [
  "fastapi",
  "pydantic-settings",
  "httpx"
]

[tool.setuptools.packages.find]
where = ["."]
