name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    types:
      - completed
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Диагностика: видит ли GitHub секреты
      - name: Debug secrets
        run: |
          echo "USERNAME is set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "TOKEN is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"

      # Логин в Docker Hub через CLI
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Сборка и пуш образа
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest


